### ISSUE TITLE
Support getInstant() method for custom (de)serializer 

### ISSUE THREAD

**Issue by foal** [DominoKit/domino-jackson#51]
Right now custom (de)serializers are created by the `new` operator:

```java
      @Override
      protected JsonDeserializer<?> newDeserializer() {
        return new InstantJsonDeserializer();
      }
```
It will be nice if domino-jackson can detect and use the `getInstance()` method, the same as for basic types e.g.

```java
      @Override
      protected JsonDeserializer<?> newDeserializer() {
        return InstantJsonDeserializer.getInstance();
      }
```

or use some flag in the `TypeRegistry.registerSerializer` method to switch between `new`/`getInstance` modes.

**Comment by vegegoku** [comment]
Sounds like something we can implement as the default behavior .. need to check though

**Comment by foal** [comment]
Hi,

I did not see any changes. The custom de/serializer still instantiate by creating a new instance even if it has factory method
```
	public static InstantJsonDeserializer getInstance() {
		return INSTANCE;
	}
```

**Comment by vegegoku** [comment]
> Hi,
> 
> I did not see any changes. The custom de/serializer still instantiate by creating a new instance even if it has factory method
> 
> ```
> 	public static InstantJsonDeserializer getInstance() {
> 		return INSTANCE;
> 	}
> ```

Are you sure you are using version `1.0.0-RC3`

**Comment by foal** [comment]
Yes.
![image](https://user-images.githubusercontent.com/458209/114299694-01863080-9abd-11eb-8bc7-6adcf26d367c.png)
But the issue is about registration custom (de)serializer. In my case for java.time.Instant. 

I register my (de)serializer by calling 
```java
		if (!TypeRegistry.containsDeserializer(INSTANT)) {
			TypeRegistry.registerDeserializer(INSTANT, ClassName.get(InstantJsonDeserializer.class));
		}
		if (!TypeRegistry.containsSerializer(INSTANT)) {
			TypeRegistry.registerSerializer(INSTANT, ClassName.get(InstantJsonSerializer.class));
		}
```

And the code is generated by `getCustomSerializer` method in the `FieldSerializerChainBuilder` class.

**Comment by vegegoku** [comment]
Seems like a misunderstanding from my side.

**Comment by foal** [comment]
It is Ok. I had to provide more details in the issue report.

**Comment by foal** [comment]
It will be great! Right now I use a very simple annotation processor: org.jresearch.gwt.time.jackson.processor (you can see it on the screenshot above)

```Java
@AutoService(Processor.class)
public class JacksonProcessor extends AbstractProcessor {
	private static final String INSTANT = Instant.class.getName();
	@Override
	public synchronized void init(ProcessingEnvironment env) {
		if (!TypeRegistry.containsDeserializer(INSTANT)) {
			TypeRegistry.registerDeserializer(INSTANT, ClassName.get(InstantJsonDeserializer.class));
		}
		if (!TypeRegistry.containsSerializer(INSTANT)) {
			TypeRegistry.registerSerializer(INSTANT, ClassName.get(InstantJsonSerializer.class));
		}
		super.init(env);
	}
	@Override
	public boolean process(final Set<? extends TypeElement> annotations, final RoundEnvironment roundEnv) {
		return false;
	}
}
```
