### ISSUE TITLE
Wrong package for JsonDeserializer/JsonSerializer

### ISSUE THREAD

**Issue by foal** [DominoKit/domino-jackson#54]
Hi, 

I have DTO in the shared GWT project and ObjectMapper in the client project. The MapperImple is generated in the correct `client` package, but JsonDeserializer/JsonSerializer pair is generated in the `shared` package, which causes the compilation error. The MapperImple assume that they will be in the same `client` package.

 
![image](https://user-images.githubusercontent.com/458209/113505067-e192c200-953c-11eb-848e-b2d02f2df6ae.png)

**Comment by vegegoku** [comment]
Generating the (de)serializer in the actual pojo is meant to avoid duplication, can you please show the compilation error?

**Comment by vegegoku** [comment]
I could repeat the case. will fix this soon

**Comment by vegegoku** [comment]
I will be publishing a new release soon
