### ISSUE TITLE
Compilation error in the eclipse with Java 11 (package exists in another module: java.base)

### ISSUE THREAD

**Issue by foal** [DominoKit/domino-jackson#58]
If a project depends on `domino-jackson-super` and try to use any class from `java.util` package the eclipse shows the error - `Class cannot be resolved to a type` 

It is happening because the project has the same package `java.util` as JVM `java.base` module

![image](https://user-images.githubusercontent.com/458209/168441636-6703a03e-43ca-4530-857a-7dccfd95290b.png)

**Comment by vegegoku** [comment]
I will test this with both GWT and j2cl as soon as possible. thank you for the fix.

**Comment by foal** [comment]
Do you have any estimates of the release date?

**Comment by vegegoku** [comment]
I will try to finish it this weekend.
