### ISSUE TITLE
add missing methods to jackson-annotations

### ISSUE THREAD

**Issue by FrankHossfeld** [DominoKit/domino-jackson#75]
We are using Spring Boot 3 in our application with domino-rest. domino-rest comes with domino-jackson which has some super sources of FasterXML's jackson-annotations.

In case of using the health endpoint of Spring Actuator this might cause an error. Spring Actuator comes with the latest version of FasterXML's jackson-annotations & data-binding. IIRC, it is version 2.15.3. 

Now calling actuator/health will cause an exception on the server:

```
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed: java.lang.NoSuchMethodError: 'java.lang.String com.fasterxml.jackson.annotation.JsonProperty.namespace()'] with root cause
java.lang.NoSuchMethodError: 'java.lang.String com.fasterxml.jackson.annotation.JsonProperty.namespace()'
```

Looking into JsonProperty of domino-jackson, it is true, the method does not exist. Depending on which library is loaded into the classpath,  it works or not. 

To avoid this race condition, domino-jackson needs to update the super sourced classes to the latest. Due to the fact, that things only get added and not removed, there will be not issue for applications using older versions of FasterXML's jackson-annotations. 

would be nice to see a fix and update in domino-rest.

**Comment by vegegoku** [comment]
Can you please share a reproducible, this is a good case to study the setup and decide on a correct direction

**Comment by FrankHossfeld** [comment]
Tried to reproduce it, but was not able - due it is a race condition. 

I'll close the issue and reopen it, once we hit the issue again.
