### ISSUE TITLE
Add support for custom serializer/deserializer

### ISSUE THREAD

**Issue by jschmied** [DominoKit/domino-jackson#79]
I have a given object structure where the apt-generator fails to create a mapping:

public interface ExternalProviderType {
	String name();
}

I have several enum implementing that interface. Of course, jackson can't map that.

I wrote custom:

ExternalProviderType_MapperImpl
ExternalProviderTypeBeanJsonDeserializerImpl
ExternalProviderTypeBeanJsonSerializerImpl

and it works. (these serializing classname and enum.name() as nested object )

Only problem is, the apt-generator tries to autogenerate own

ExternalProviderTypeBeanJsonSerializerImpl

in output folder and fails. If I remove this file, anything is fine in a IDE.

A maven build fails of course.

What I need is a way to tell the apt-generator not to create serializer/deserializer if there is one already.

Any recomendations?

@JsonSerialize will not be supported I guess

**Comment by vegegoku** [comment]
link #51

**Comment by jschmied** [comment]
works for me

**Comment by vegegoku** [comment]
Documentations are now available here
https://dominokit.com/solutions/domino-jackson/v1/docs/custom-mappers
